### ISSUE TITLE
`Rd²` -> `Rd⁻²` in Docs/Quasigeostrophic equations

### ISSUE THREAD

**Issue by navidcy** [pvthinker/Fluid2d#8]
In the docs:

http://pagesperso.univ-brest.fr/~roullet/fluid2d/docs/model_equations.html#quasi-geostrophic-equations

the streamfunction-PV relationship has a typo. It should read

```
 ... + Rd⁻² ψ + ...
```

**Comment by pvthinker** [comment]
Hi Navid,

Thank you for spotting this typo. It's fixed. Meanwhile, I'm realizing that it would be cool to have the source of the documentation in the repo. Sometimes, I'll do it.

Guillaume
